### ISSUE TITLE
Gtk Shell Theme Dark version - Dots on Dash to Dock disappears

### ISSUE THREAD

**Issue by SirFmac** [pop-os/gtk-theme#111] opened 2017-12-27 23:56 UTC
Distribution - Ubuntu 17.10
Desktop environment - Gnome
Pop version - 3.0.1

Dash to dock gtk shell theme.

If I use light theme, the dots of active applications appears, but if I use dark version the dots disappear.

Light version
![screenshot from 2017-12-27 23-55-35](https://user-images.githubusercontent.com/27894544/34396346-7906a0f4-eb61-11e7-8840-ab4fc0fb51c3.png)

Dark version
![screenshot from 2017-12-27 23-55-39](https://user-images.githubusercontent.com/27894544/34396375-dfe3c28e-eb61-11e7-99c3-a4cd39f1de18.png)

**Comment by isantop** [comment] 2018-01-04 03:15
This is being caused by the same bug as #108, and is fixed in the current version of Pop_GTK

**Closed by isantop** 2018-01-04 03:15 UTC
