### ISSUE TITLE
gnome weather notification not displaying properly

### ISSUE THREAD

**Issue by wsamh** [pop-os/gtk-theme#580] opened 2022-05-13 06:23 UTC
the gnome weather applet in the notification area is showing boxes in place of the sun icon. 

PRETTY_NAME="Pop!_OS 22.04 LTS"

pop-gtk-theme 5.5.1~1651080726~22.04~1509852

Pop Gtk theme - Pop Gtk theme used by System76

ID: org.gtk.Gtk3theme.Pop
Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
Arch: x86_64
Branch: 3.22
Origin: flathub
Collection: org.flathub.Stable
Installation: user
Installed: 1.1 MB

Commit: 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d856a5efb998b318a5
Parent: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db97b5394ba3a501bea3
Subject: add flathub.json (84e0033a)

![Screenshot from 2022-05-12 22-59-11](https://user-images.githubusercontent.com/67978594/168223417-71f220f5-2df9-48b2-82d2-8504e867bbab.jpeg)

**Comment by leviport** [comment] 2022-05-16 19:14
Duplicate of https://github.com/pop-os/pop/issues/2378

**Closed** 2022-05-16 19:14 UTC
