### ISSUE TITLE
Transparent menu background

### ISSUE THREAD

**Issue by octavioln** [pop-os/gtk-theme#273] opened 2019-02-08 16:23 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Instalados: 3.22.30-1ubuntu1
  Candidato:  3.22.30-1ubuntu1
  Tabla de versión:
 *** 3.22.30-1ubuntu1 500
        500 http://mx.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
Gnome Desktop 3.28.2

**Pop version (run ```apt policy pop-gtk-theme```):**
 4.1.1~1549561776~18.04~20fd8b0

**Related Application and/or Shell theming (or name of widget)**
All Pop themes (Pop, Pop-slim, Pop-light, Pop-light-slim, Pop-dark, Pop-dark-slim)

**Actual issue**
Deskop right-click menu is transparent
![Uploading IMG_3247.JPG…]()

**Steps to reproduce**
Right click on a clear area of the desktop

**Comment by isantop** [comment] 2019-02-08 22:10
This bug is a duplicate of #272

**Closed by isantop** 2019-02-08 22:10 UTC
