### ISSUE TITLE
Close button in Firefox misaligned

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#233] opened 2018-11-04 00:24 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.1-1ubuntu2

**Desktop environment:**
Gnome

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
4.0.0

**Related Application and/or Shell theming (or name of widget)**
Firefox

**Actual issue**
In the "Customize Firefox" page in Firefox, after disabling the Title Bar and selecting `Done`, the "X" in at the top of the window appears outside of the orange circle. This can be seen in the following screenshot.

![screenshot from 2018-11-03 18-08-40](https://user-images.githubusercontent.com/7460774/47958671-67d60300-df95-11e8-9d80-d9dac46f063b.png)

**Steps to reproduce**
1. Open Firefox.
2. Select the Hamburger menu
3. Select "Customize..."
4. At the bottom of the page, uncheck "Title Bar".\
5. Select "Done".

**Expected behavior**
Close "X" stays in the middle of the orange circle.

**Behavior in Adwaita**
This issue does not happen in Adwaita.

**Comment by evertiro** [comment] 2018-11-05 23:40
![screenshot from 2018-11-05 17-38-52](https://user-images.githubusercontent.com/36433/48033666-d34cdb80-e121-11e8-8804-913402103040.png)
Confirmed. Interestingly, if you hit <kbd>Alt</kbd>, or otherwise interact with the window itself, it fixes itself.

**Comment by isantop** [comment] 2018-11-06 16:37
@brs17 This issue does happen with Adwaita. It's a bug in the CSD implementation in Firefox. To trigger it, you need to change the window from maximized to un-maximized. When that state change happens, this issue will occur.

It's less noticeable in Adwaita because they don't use contrasting colors for the tab/titlebar and the tab's toolbar.

Maximized > Un-maximized: 
![screenshot from 2018-11-06 09-32-28](https://user-images.githubusercontent.com/5883565/48078794-5106fa80-e1a7-11e8-9bda-3ae6dfa75914.png)
_note how the darker grey from the toolbar creeps up a few pixels into the tab bar._

After Tab: 
![screenshot from 2018-11-06 09-32-36](https://user-images.githubusercontent.com/5883565/48078864-76940400-e1a7-11e8-84cc-34b783ab1b84.png)

Un-maximized > Maximized:
![screenshot from 2018-11-06 09-32-49](https://user-images.githubusercontent.com/5883565/48078896-87dd1080-e1a7-11e8-8ce7-6a444b09092a.png)

After Tab:
![screenshot from 2018-11-06 09-32-58](https://user-images.githubusercontent.com/5883565/48078922-91667880-e1a7-11e8-9cff-19a486b6d024.png)

**Comment by isantop** [comment] 2019-10-23 17:11
This bug does not happen anymore and has been fixed in Firefox.

**Closed by isantop** 2019-10-23 17:11 UTC
Labels: bug, upstream
