### ISSUE TITLE
Mouse hovering issue with corners (resizing feature)

### ISSUE THREAD

**Issue by phocean** [pop-os/gtk-theme#167] opened 2018-05-23 07:35 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installé : 3.22.30-1ubuntu1
  Candidat : 3.22.30-1ubuntu1
 Table de version :
 *** 3.22.30-1ubuntu1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

Ubuntu Mate 18.04

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

Pop!_GTK+ Version 3.1.1

**Related Application and/or Shell theming (or name of widget)**

N/A

**Actual issue**

Corner mouse hover, used to resize windows, do not work.
My guess is that there is too little space left because of the close widget size and position.

**Steps to reproduce**

At least in Mate, just enable the theme as "window borders" and try to resize windows from any corner.

**Expected behavior**

The mouse cursor should change when hovering a corner and allow resizing.

**Behavior in Adwaita**

It works with most themes, including Adwaita, Numix, Arc.  I found this issue in some other themes, with less impact (difficult to catch but works) : Vimix, Stylish

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment] 2018-10-15 22:31
Closing as this is a duplicate of #175

**Closed by isantop** 2018-10-15 22:31 UTC
Labels: blocked, bug
