### ISSUE TITLE
Pop!_Shop: Footer text is too lightly colored

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#359] opened 2019-10-14 20:19 UTC
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
Pop!_Shop

**Actual issue**
On an application's page, the footer information (License, Homepage, Report a Problem, Help) is in a very light colored text which makes it look like they are not clickable buttons, when in fact they are.

![footer_low_vis](https://user-images.githubusercontent.com/7460774/66780222-87f09080-ee8d-11e9-804a-b235f1fabc90.png)

**Expected behavior**
Darker font color

**Comment by isantop** [comment] 2019-10-15 16:36
Duplicate of #325

**Closed by isantop** 2019-10-15 16:36 UTC
Labels: 19.10
