### ISSUE TITLE
Text in Calendar is rendered dark on a dark background when using default themes

### ISSUE THREAD

**Issue by John15321** [pop-os/gtk-theme#496] opened 2021-01-18 13:10 UTC
**Describe the problem:**
My calendar renders text as dark on a dark background:
![image](https://user-images.githubusercontent.com/56229312/104919262-3db26500-5996-11eb-9367-5c17d1e6a87d.png)

**Steps to reproduce:**
I didn't do anything special. Its just how its behaving since the beginning. Here are my themes settings:
![image](https://user-images.githubusercontent.com/56229312/104919315-591d7000-5996-11eb-95c8-a646584b483a.png)

![image](https://user-images.githubusercontent.com/56229312/104919342-633f6e80-5996-11eb-8ee0-a1e5a1492b71.png)

![image](https://user-images.githubusercontent.com/56229312/104919371-6e929a00-5996-11eb-82d2-70339a99bd75.png)

Chancing them did not help.
People on pop os forum confirmed they can also reproduce this:
https://pop-planet.info/forums/threads/text-in-my-calendar-is-dark-on-dark-background-and-i-cannot-read-it.1280/#post-5931
**Distribution:**
```bash
PRETTY_NAME="Pop!_OS 20.10"
```

**Pop version:**
```bash
$ apt policy pop-gtk-theme | grep -i installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

  Installed: 5.3.1~1607460951~20.10~70c0a52
```
```bash
$     flatpak info org.gtk.Gtk3theme.Pop
error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed
```

My inxi info:
```bash
$ inxi -Fxxx
System:
  Host: pop-os Kernel: 5.8.0-7630-generic x86_64 bits: 64 compiler: gcc 
  v: 10.2.0 Desktop: N/A wm: gnome-shell dm: GDM3 3.38.1 
  Distro: Pop!_OS 20.10 base: Ubuntu 20.10 Groovy 
Machine:
  Type: Desktop Mobo: ASRock model: H110M-DVS R3.0 
  serial: <superuser/root required> UEFI [Legacy]: American Megatrends 
  v: P1.20 date: 04/17/2017 
CPU:
  Info: Quad Core model: Intel Core i5-7400 bits: 64 type: MCP 
  arch: Kaby Lake rev: 9 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 24000 
  Speed: 800 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 
Use of uninitialized value $working[3] in substitution (s///) at /usr/bin/inxi line 21120.
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 455.38 
  bus ID: 01:00.0 chip ID: 10de:1c03 
  Display: x11 server: X.Org 1.20.9 compositor: gnome-shell driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1: 1920x1080~60Hz 
  2: 1920x1080~75Hz s-dpi: 81 
  OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 455.38 
  direct render: Yes 
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: ASRock 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a170 
  Device-2: NVIDIA GP106 High Definition Audio driver: snd_hda_intel 
  v: kernel bus ID: 01:00.1 chip ID: 10de:10f1 
  Device-3: Corsair Corsair VOID PRO Surround USB Adapter type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-10:5 chip ID: 1b1c:0a18 
  serial: 00000000 
  Device-4: C-Media USB Audio Device type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-7:2 chip ID: 0d8c:0126 
  Sound Server: ALSA v: k5.8.0-7630-generic 
Network:
  Device-1: Realtek RTL8192CE PCIe Wireless Network Adapter 
  driver: rtl8192ce v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8178 
  IF: wlp2s0 state: down mac: 74:da:38:c1:9d:43 
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASRock driver: r8169 v: kernel port: c000 bus ID: 03:00.0 
  chip ID: 10ec:8168 
  IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: 70:85:c2:45:72:8b 
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:01 
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:08 
Drives:
  Local Storage: total: 1.38 TiB used: 311.24 GiB (22.1%) 
  ID-1: /dev/sda vendor: Silicon Power model: SPCC Solid State Disk 
  size: 476.94 GiB speed: 6.0 Gb/s serial: C6380799116A00116718 rev: 61.3 
  scheme: MBR 
  ID-2: /dev/sdb vendor: Crucial model: CT1000MX500SSD1 size: 931.51 GiB 
  speed: 6.0 Gb/s serial: 1919E20206DF rev: 023 scheme: MBR 
Partition:
  ID-1: / size: 464.51 GiB used: 311.24 GiB (67.0%) fs: ext4 dev: /dev/sda1 
Swap:
  ID-1: swap-1 type: partition size: 4.00 GiB used: 0 KiB (0.0%) 
  priority: -2 dev: /dev/dm-0 
Sensors:
  System Temperatures: cpu: 32.0 C mobo: N/A gpu: nvidia temp: 38 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 25% 
Info:
  Processes: 314 Uptime: 2h 48m Memory: 15.59 GiB used: 7.45 GiB (47.8%) 
  Init: systemd v: 246 runlevel: 5 Compilers: gcc: 10.2.0 alt: 10 
  Packages: 3721 apt: 3662 flatpak: 56 snap: 3 Shell: Bash v: 5.0.17 
  running in: gnome-terminal inxi: 3.1.07 
```

**Comment by jacobgkau** [comment] 2021-01-19 15:56
This would be fixed by https://github.com/pop-os/gtk-theme/pull/488, although that PR also breaks some label colors since it sets the text color based only on the theme and not on the label color. (Currently, the light theme uses legible text color depending on the label color.)

**Comment by John15321** [comment] 2021-01-19 16:46
> This would be fixed by #488, although that PR also breaks some label colors since it sets the text color based only on the theme and not on the label color. (Currently, the light theme uses legible text color depending on the label color.)

I see. I don't want to switch my whole systems there to light (I like having eyes lol). Is there a way to just switch it for the calendar so that I can actually use it? Because at this point you just cant see what those events even are

**Comment by jacobgkau** [comment] 2021-01-20 00:31
@John15321 I've fixed the PR that I previously linked. If it passes review, you will receive that fix through a regular software update.

Until then, yes, you can launch `GTK_THEME=Pop:light gnome-calendar` to run the app with the Pop Light theme (I had to do `killall gnome-calendar` first to make an older instance in the background go away before that worked.)

**Comment by John15321** [comment] 2021-01-20 01:47
@jacobgkau  Great 🥰! Btw Im a programmer myself and I have some (even professional) experience. How can I get into helping? Because I constantly see stuff that needs more polish on distros I use (I use PopOS and Manjaro) and they all use GNOME.

**Comment by John15321** [comment] 2021-01-20 02:03
Oh and btw. Im seeing this exact same bug woth color rendering on my laptop with Manjaro GNOME. So is that the calendar app itself issue or what?

**Comment by jacobgkau** [comment] 2021-01-20 03:42
> Im seeing this exact same bug woth color rendering on my laptop with Manjaro GNOME. So is that the calendar app itself issue or what?

I don't know what theme Manjaro uses off the top of my head, but I am seeing the bug in Adwaita Dark, the default dark theme for GNOME. We're fixing the bug in Pop Dark with that PR, but the Adwaita Dark bug would need to be fixed upstream, I believe in the Calendar app's `Adwaita.css` file: https://gitlab.gnome.org/GNOME/gnome-calendar/-/blob/master/src/theme/Adwaita.css I did try changing `@theme_fg_color;` to `black` on [line 220](https://gitlab.gnome.org/GNOME/gnome-calendar/-/blob/442df955c18e9709e624e43dbb8b56b8ba97ffd4/src/theme/Adwaita.css#L220) (I would have submitted a merge request upstream if it was that simple), but making that change and rebuilding the app didn't seem to fix the problem in Adwaita Dark, so something else might be going on there.

> Im a programmer myself and I have some (even professional) experience. How can I get into helping? Because I constantly see stuff that needs more polish on distros I use (I use PopOS and Manjaro) and they all use GNOME.

If you want to contribute to GNOME directly, you would want to browse their source code, read open issues, and make merge requests on their GitLab instance: https://gitlab.gnome.org/GNOME 

As for Pop!_OS, all of the software developed for Pop here at System76 is open-source and pull requests are always welcome. If you're a professional programmer, you may already have some experience using git, but if not, looking up some guides online about using git, GitHub, and GitLab would probably be helpful. After that, Pop!_OS software is generally found in the [Pop!_OS organization](https://github.com/pop-os), and some more System76-specific repositories are found in the [System76 organization](https://github.com/system76) (if a component you're looking at in Pop is not listed in the Pop!_OS organization, then it's likely being inherited from Ubuntu and you would want to go upstream instead.)

**Comment by isantop** [comment] 2021-01-25 16:41
@John15321 #488 was just merged into master this morning, so it should be available in your regular software updates within a few days. If that update doesn't fix this, please feel free to reopen this issue and we'll evaluate the problem further.

Thanks for your issue and for being a Pop user!

**Closed by isantop** 2021-01-25 16:41 UTC

**Comment by John15321** [comment] 2021-01-25 18:01
@isantop Thank you very much 😀I will inform you when I get the update and if its fixed! Im very happy that you guys can react and fix things! ♥

**Comment by John15321** [comment] 2021-01-25 21:32
@isantop I just updated and it works!!!! Thank you so much! <3 Im so glad that people that maintain this distro actually care 🥰
![image](https://user-images.githubusercontent.com/56229312/105768725-15f66a80-5f5d-11eb-95aa-a876c6278b6f.png)

**Comment by jdabgotra** [comment] 2022-02-18 00:29
@isantop It seems fixing this bug might have created the same problem on the light theme, with white color on a white background. 

![image](https://user-images.githubusercontent.com/1064169/154594415-9ee17d9d-0eec-4bb9-9b6d-6c80f164ad02.png)

**Comment by jacobgkau** [comment] 2022-02-18 01:15
@jdabgotra The issue you're seeing now is likely not caused by the fix for this 1+-year-old bug. You may want to open a new issue.
