### ISSUE TITLE
Extra huge border on i3-wm

### ISSUE THREAD

**Issue by jrgparamo** [pop-os/gtk-theme#253] opened 2018-12-13 22:33 UTC
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
NAME="Antergos Linux"
PRETTY_NAME="Antergos Linux"
ID=antergos
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://antergos.com/"

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
GTK 3.24.2

**Desktop environment:**
i3-wm

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.
....

**Related Application and/or Shell theming (or name of widget)**
Nautilus, gnome-calculator, gnome-disks, all gnome/gtk theme related apps basically

**Actual issue**
![screenshot from 2018-12-13 16-16-40](https://user-images.githubusercontent.com/3992139/49971629-b6f84780-fef4-11e8-8c6f-18faa7a278d9.png)

![screenshot from 2018-12-13 16-17-58](https://user-images.githubusercontent.com/3992139/49971013-aa72ef80-fef2-11e8-96f3-4ae2d7020ef5.png)

**Steps to reproduce**
1. Apply Pop GTK theme via lxappearance
2. Open any gnome app
3. Giant borders

**Expected behavior**
No giant boarders or margins like Adwaita theme

**Behavior in Adwaita**
![screenshot from 2018-12-13 16-13-50](https://user-images.githubusercontent.com/3992139/49971560-89130300-fef4-11e8-8ce1-d349bdd549eb.png)

![screenshot from 2018-12-13 16-31-55](https://user-images.githubusercontent.com/3992139/49971622-b2339380-fef4-11e8-9bd8-1ba14ff10a17.png)

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment] 2018-12-17 18:34
Thanks for your issue! This is a duplicate of #250, so I'm going to close this issue and track it there.

**Closed by isantop** 2018-12-17 18:34 UTC
