### ISSUE TITLE
The sidebar is too wide

### ISSUE THREAD

**Issue by pierrejacquet** [pop-os/gtk-theme#152] opened 2018-04-28 09:43 UTC
* Distribution - Ubuntu 18.04 LTS
 * Gtk+ 3.0 version -   3.22.30-1ubuntu1
 * Desktop environment - Gnome 
 * Pop version - Pop!_GTK+ Version 3.1.0
 
**Related Application and/or Shell theming (or name of widget)**

Desktop sidebar

**Actual issue**
The sidebar is too wide. I'm running the last version of ubuntu. I can't reproduce it with other shell themes.

![screenshot from 2018-04-28 11-32-31](https://user-images.githubusercontent.com/28867580/39394972-b74e048e-4ad8-11e8-8845-dbd60f86b359.png)

I guess the icons should be centered and/or the sidebar should not be that large. Other versions of the theme give the same results.

Is it a problem from my side ?

**Comment by pierrejacquet** [comment] 2018-04-28 09:51
In addition, the colors in the drop-down menu at the top right seem buggy (under the same conditions).
![screenshot from 2018-04-28 11-49-56](https://user-images.githubusercontent.com/28867580/39395083-7deb12f2-4ada-11e8-8de2-e1982834211a.png)

**Comment by yopspanjers** [comment] 2018-04-28 13:12
I've got the same problems on ubuntu 18.04 with the dock (Dash to dock) on the bottom.

**Comment by letheed** [comment] 2018-04-28 13:14
I just updated and I can confirm the shell theme has wrong colors in the menus and the "Dash to Dock" dock is way too wide. Had no problem with 17.10.

**Comment by aden-young** [comment] 2018-05-09 15:15
The latest fix applied in https://github.com/pop-os/gnome-shell-theme/pull/24 has reduced the size of the sidebar, but I can still see a couple of issues, namely:
1. The "show applications" button cannot be clicked by clicking the very bottom left pixel of the screen, this is the behaviour of the Ubuntu Dock
2. The dock is actually wider when the "Shrink the dash" option is ticked in the dash to dock settings

**Comment by isantop** [comment] 2018-05-14 17:40
1. I'll have to investigate this.

2. Yeah, the new theme actually removes all of the side padding on the dock items. I think it really cleans up the launcher in the theme. Unfortunately, DTD overrides the theme and sets it's own padding in when the shrink option is applied, which is usually smaller than most themes, but not a guarantee. As such, it might be better to treat that option as reversed in Pop, since the default is for it to be as compact as possible.

**Comment by d4mr** [comment] 2018-06-13 18:59
The issue still remains in the version I am using from the PPA.

![screenshot from 2018-06-14 00-28-15](https://user-images.githubusercontent.com/16459486/41372100-ee8a53e8-6f69-11e8-95fa-cb9e5037f405.png)
![screenshot from 2018-06-14 00-28-39](https://user-images.githubusercontent.com/16459486/41372110-f738643a-6f69-11e8-9ac7-0e53d59aaf33.png)

**Comment by isantop** [comment] 2018-06-13 19:43
@d4mr I think that's because of the custom image present for the show-applications button. The dash isn't layed out in the most intuitive way, and that's the real cause of the problem.

**Comment by zl-kolev** [comment] 2018-07-08 20:03
It seems that somehow the width remains unchainged...
![screenshot from 2018-07-08 23-02-16](https://user-images.githubusercontent.com/31390751/42423452-20c04438-8303-11e8-8913-c4bbcf2113d9.png)

**Comment by FoseFx** [comment] 2018-08-20 13:39
> @d4mr I think that's because of the custom image present for the show-applications button. The dash isn't layed out in the most intuitive way, and that's the real cause of the problem.

Indeed, I removed it using dconf (`org.gnome.shell.extentions.dash-to-dock.show-show-apps-button`). To get into the apps menu now I use the `Super-A` shortcut.

**Comment by isantop** [comment] 2018-08-21 15:34
Closing this issue as the relevant parts of the theme (The GNOME Shell theme) are now handled in a separate repository.

**Closed by isantop** 2018-08-21 15:34 UTC
Labels: bug, fix-committed

**Comment by letheed** [comment] 2018-08-21 19:32
@isantop I coudln't find a matching issue in the shell repo, should one be opened?

**Comment by isantop** [comment] 2018-08-21 19:39
@letheed I haven't been able to replicate this with the latest copies of the theme. I think the issues that remain have to do with Ubuntu's custom dash-to-dock, which this theme doesn't work on supporting.

**Comment by letheed** [comment] 2018-08-21 19:43
I'm using upstream dash to dock, not the "Ubuntu Dock" extension. I'm also on a regular "Gnome session on Xorg", not the tweaked Ubuntu one.

**Comment by isantop** [comment] 2018-08-21 21:03
Can you send a screenshot of the dock with the misalignment?

**Comment by letheed** [comment] 2018-08-21 21:14
@isantop I actually just opened an issue on the shell repo.

**Comment by haykerman** [comment] 2018-09-01 21:06
Any update on this?

**Comment by haykerman** [comment] 2018-09-01 22:33
@letheed, thanks.
