### ISSUE TITLE
(shell) standard and light variants

### ISSUE THREAD

**Issue by DarthWound** [pop-os/gtk-theme#80] opened 2017-11-05 03:56 UTC
Hello, is there any tangible difference between "Pop" and "Pop-light" shell themes?
If not, is this necessary to have both?

**Comment by isantop** [comment] 2017-11-06 16:32
There isn't technically a difference, however it's installed due to the way the makefile is structured. If you'd like to take a look at it and change that, that would certainly be fine! :)

**Comment by DarthWound** [comment] 2017-11-06 18:00
Yeah because it's based on Materia which have both "standard" and "light", I understand that, was asking in case I was missing something.

Maybe "light" or "standard" could have a transparent panel (like Materia) to make a difference. If not, then we agree that it would be less confusing to ditch the "light" variant. Removing every file related to "light" variant isn't enough though? Can't see that much in the makefile at first view.

**Comment by isantop** [comment] 2017-11-06 18:11
The problem is that Pop-Light is very different from regular Pop. And we want to keep that version. The GNOME Shell theme just kind of comes along for the ride with that.

**Comment by DarthWound** [comment] 2017-11-06 18:23
Oh, my bad, of course you're right about GTK :D would require too much work to separate them.

Well as I said previously maybe making panel less opaque could be nice. A lot of themes do that for their "light" variant, GNOME 3.26 comes this way too, and it seems that people like it.

**Comment by DarthWound** [comment] 2017-11-06 18:34
I agree that the light GNOME Shell theme doesn't take that much space, it was just for consistency.

But I disagree on "_There aren't other themes that do that_", as I said default 3.26 Adwaita is transparent and almost every theme based on Materia have a transparent _(not full transparency)_ for their light variant, not counting several other themes not related to Materia. But it was just a suggestion like any other ^^ I don't care that much about that, I stick to standard variant when I use Pop themes.

**Comment by isantop** [comment] 2017-11-06 18:53
I should have clarified that there aren't other Pop themes that do that. I'm aware that many other themes  have transparent panels, but that's not something that really fits in with the Pop design right now.

**Comment by DarthWound** [comment] 2017-11-06 19:00
Sure, I understand :)

**Comment by isantop** [comment] 2018-08-21 15:38
Closing because of old-age and moving the shell theming to a [separate repository](https://github.com/pop-os/gnome-shell-theme).

**Closed by isantop** 2018-08-21 15:38 UTC
Labels: good first issue, wishlist
