### ISSUE TITLE
Some menu items don't have enough contrast

### ISSUE THREAD

**Issue by kylecorry31** [pop-os/gtk-theme#260] opened 2018-12-24 13:54 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
GNOME 3.30.2

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**
Atom

**Actual issue**
In Atom, the menu items are black with a warm gray background, making them hard to read.
![screenshot from 2018-12-24 08-50-05](https://user-images.githubusercontent.com/5938560/50400963-2d990e80-0759-11e9-9713-ff5bafd5f3d8.png)

**Steps to reproduce**
Open the Atom text editor and look at the title bar.

**Expected behavior**
The title bar items are white with the warm gray background.

**Behavior in Adwaita**
Unknown

**Other Note (feature-request, question, etc...)**

**Comment by brs17** [comment] 2018-12-24 15:51
This does not seem to be an issue with the Adwaita application theme.

**Comment by isantop** [comment] 2019-01-02 22:13
Duplicate of #230, upstream electron bug tracked in electron/electron#15194

**Closed by isantop** 2019-01-02 22:13 UTC
Labels: bug, duplicate, upstream
