### ISSUE TITLE
Poor contrast in Disks

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gtk-theme#543] opened 2021-09-17 20:56 UTC
![image](https://user-images.githubusercontent.com/3430283/133852609-8315efb5-2baf-4ef6-ae6c-e2074021104f.png)

**Comment by leviport** [comment] 2021-09-17 21:11
This has been open for a while: https://github.com/pop-os/gtk-theme/issues/373

**Comment by leviport** [comment] 2021-09-20 15:59
I'm going to close this as a duplicate of #373

**Closed by leviport** 2021-09-20 15:59 UTC
