### ISSUE TITLE
Tab accent colors are solid black after updating to Firefox 87

### ISSUE THREAD

**Issue by 808-cowbell** [pop-os/gtk-theme#507] opened 2021-04-03 17:41 UTC
**Describe the problem:** After updating Firefox on my Pop installs a few days ago, the accent color that appears above active tabs seems to have broken; right now it's `#000000`, but I think it used to be `#63b1bc`. If I downgrade Firefox to a version prior to 87, the accent color appears to work correctly. The inactive highlight color also seems to have broken. I can reproduce this on both the dark and light variants, and I can reproduce this on multiple computers running 20.04 LTS. I cannot reproduce this on other GTK themes.

![Screenshot from 2021-04-03 11-20-36](https://user-images.githubusercontent.com/47785671/113486563-c490bd00-9470-11eb-93af-a2c148957ee9.png)

**Steps to reproduce:**
1. Upgrade to Firefox 87

**Distribution:**

Pop!_OS 20.04 LTS

**Pop version:**

5.2.0\~1599689740\~20.04\~11b9d22

**Comment by jacobgkau** [comment] 2021-04-07 18:13
Running Firefox 86 to confirm, the previous accent colors were actually `#48b9c7` on light mode and `#94ebeb` on dark mode:

![Screenshot from 2021-04-07 09-16-32](https://user-images.githubusercontent.com/7199422/113904726-9cb29980-978f-11eb-86b2-a7a886fff6fc.png)

![Screenshot from 2021-04-07 09-16-10](https://user-images.githubusercontent.com/7199422/113904723-9ae8d600-978f-11eb-8490-b4cdd91ef5f9.png)

These are `$selected_bg_color` in `_colors.scss`. For some reason, Firefox now appears to be using `$selected_fg_color` for these elements instead (if I change `$selected_fg_color`, the tab accent and focused URL bar border change.) Our foreground color is set the way we want it, and I haven't figured out how to override the tab color from the GTK theme yet. What I do know is:

- This issue is not occurring in Adwaita.
- If I change `$selected_fg_color` to `#fff` to match Adwaita, then it's ignored, and the correct accent color is used instead. I'm not sure why this is happening, and whether it's happening in Firefox/MozillaGtkWidget or somewhere else.

**Comment by jacobgkau** [comment] 2021-04-07 20:27
I believe this revision was the cause of this regression: https://hg.mozilla.org/mozilla-central/rev/d548eba4ee80aab8ae8954fa135ec383402afffe 

```
Make Linux tab bar use the darker of the highlight / highlighttext colors. r=dao

Some GTK themes use very soft colors for selection backgrounds, using
darker colors for the text. This makes the tab and focus outlines in the
tab bar not have sufficient contrast with usual backgrounds.
```

```
+    // Accent is the darker of the selection background / foreground.
+    mAccentColor = mTextSelectedBackground;
+    mAccentColorForeground = mTextSelectedText;
+    if (RelativeLuminanceUtils::Compute(mAccentColor) >
+        RelativeLuminanceUtils::Compute(mAccentColorForeground)) {
+      std::exchange(mAccentColor, mAccentColorForeground);
+    }
```

This explains why the value of `$selected_fg_color` determines whether `$selected_fg_color` or `$selected_bg_color` is used for the accents. The remaining question is how to override that decision.

**Comment by 808-cowbell** [comment] 2021-04-22 17:14
For those viewing this thread because they're having the same problem, [this userChrome tweak](https://bugzilla.mozilla.org/show_bug.cgi?id=1703679#c3) suggested in Firefox's bug tracker mostly mitigated the problem for me!

**Comment by isantop** [comment] 2021-10-11 20:08
This should be fixed in both the latest version of the theme and Firefox, so we're closing it for now.

**Closed by isantop** 2021-10-11 20:08 UTC
Labels: gtk
