### ISSUE TITLE
Transparent Background on Drop Down in GNUCash

### ISSUE THREAD

**Issue by ardichoke** [pop-os/gtk-theme#467] opened 2020-08-13 15:00 UTC
**Describe the problem:**
The account selection drop-down menus in GNUCash have a transparent background when using Pop OS themes (both dark and light), this makes the text illegible. Interestingly, if you change focus to another window while these drop-downs are open, the background on them becomes solid as expected.

![Screenshot from 2020-08-13 10-56-20](https://user-images.githubusercontent.com/112836/90150481-b5c78f80-dd53-11ea-9cd8-6ec5808c2acd.png)
![Screenshot from 2020-08-13 10-56-32](https://user-images.githubusercontent.com/112836/90150492-b829e980-dd53-11ea-91d7-34275c75a288.png)

**Steps to reproduce:**
1. With a Pop OS theme applied, launch GNUCash
2. Open an account
3. Click on the "Transfer" drop-down in the ledger

**Distribution:**

```
PRETTY_NAME="Pop!_OS 20.04 LTS"
```

**Pop version:**

```

[502]$ apt policy pop-gtk-theme | grep -i installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

  Installed: 5.2.0~1593549084~20.04~8c31be9

[503]$     flatpak info org.gtk.Gtk3theme.Pop
error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed
```

**Comment by isantop** [comment] 2020-08-26 16:40
What kind of result do you get if you use GNUCash with the Adwaita theme? You can temporarily run it with the Adwaita theme using this command:

`GTK_THEME=Adwaita gnucash`

**Comment by ardichoke** [comment] 2020-08-26 17:40
It works as expected, with a non-transparent background and readable text even when GNUCash has focus. I actually switched my theme over to Adwaita entirely because of this bug, since I spend a non-trivial amount of time using GNUCash and this bug makes it very hard to work with.

**Comment by isantop** [comment] 2020-08-27 14:54
Thanks for checking that! That helps a lot in figuring out where the issue is being caused. I've got a new commit ready to go which will be released soon which fixes this issue.

**Closed** 2020-09-09 22:15 UTC
Labels: 20.04, bug, fix-committed, gtk

**Comment by indrekots** [comment] 2020-11-19 20:59
I seem to be having a similar issue, but for me, I'm experiencing transparent dropdowns only while using Pop OS dark theme. The transparency issue does not occur when using the light theme.

```
$ apt policy pop-gtk-theme
pop-gtk-theme:
  Installed: 5.3.0~1605227705~20.10~50f789b
```

The following image depicts the dark theme.
![Screenshot from 2020-11-19 22-48-54](https://user-images.githubusercontent.com/2362349/99722735-c22d5800-2ab9-11eb-85df-d2b35fbc4f8b.png)

Similar to what @ardichoke reported, when the GnuCash window loses focus, the dropdown becomes readable, although it's not fully opaque.
![Screenshot from 2020-11-19 22-49-12](https://user-images.githubusercontent.com/2362349/99722802-e38e4400-2ab9-11eb-9b7b-1a5bc1bdaf50.png)

When switching the theme to Pop OS light, then I don't see any issues. 
![Screenshot from 2020-11-19 22-50-01](https://user-images.githubusercontent.com/2362349/99723118-69aa8a80-2aba-11eb-9c5a-a9ab460a6185.png)

Anything else I could provide to help debug the issue?

**Comment by jacobgkau** [comment] 2020-11-19 23:13
Interesting. I am not seeing the same issue with the same version of the theme installed:

![gnucash-working](https://user-images.githubusercontent.com/7199422/99735003-1536e900-2a81-11eb-82d7-cba2ff5e2666.png)

@indrekots We would probably need to figure out what's different between your machine and other machines to cause this. If you create a new user account (Settings -> Users), log out of your normal account and into the new account, and open GNUCash, does the issue occur there?

**Comment by indrekots** [comment] 2020-11-22 17:07
With a brand new user, I didn't observe this issue. Perhaps it could be due to some plugin? I'll try to disable them and report back.

**Comment by indrekots** [comment] 2020-12-09 07:46
Not sure what has changed on my computer but now It works as intended. Therefore, disregard my comments.
