### ISSUE TITLE
No manual window resizing possible with mouse.

### ISSUE THREAD

**Issue by anjanik012** [pop-os/gtk-theme#163] opened 2018-05-16 10:54 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution:**

NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version**

libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://in.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

MATE 1.20.1

**Pop version:**
Pop!_GTK+ Version 3.1.0

**Related Application and/or Shell theming (or name of widget)**
Windows
![screenshot at 2018-05-16 16-00-04](https://user-images.githubusercontent.com/24349858/40112060-7172d34c-5922-11e8-8212-899c150596fa.png)

**Actual issue**
No manual resizing of windows is  possible.
The windows once opened in the default size remain at default size.
However maximization and minimization is possible . Manual resizing is not. 

**Steps to reproduce**
Open an application.
![screenshot at 2018-05-16 16-00-04](https://user-images.githubusercontent.com/24349858/40112179-d03698f0-5922-11e8-92f0-f7b2862a7235.png)

move the mouse pointer to the bottom right hand side of the window  or to the bottom to resize.
![screenshot at 2018-05-16 16-06-31](https://user-images.githubusercontent.com/24349858/40112302-32ceff8e-5923-11e8-8619-cb2d2e1cbf35.png)

Hold left click on mouse and start dragging. No resizing.

**Expected behavior**
Resizing tool should be appeared as in default abmbiance theme.
![peek 2018-05-16 16-22](https://user-images.githubusercontent.com/24349858/40112978-74eed0f4-5925-11e8-8d2d-e7f48c8759d1.gif)

**Comment by isantop** [comment] 2018-05-16 16:16
Thanks for filing an issue! Since Pop doesn't use any window border, windows get a small (~8px) margin to serve as the resize area. As such, the resize area is slightly outside of the window, and starts at the very edge. 

![peek 2018-05-16 10-16](https://user-images.githubusercontent.com/5883565/40129716-41d9bb6c-58f2-11e8-9be0-e7fea844177e.gif)

**Comment by anjanik012** [comment] 2018-05-16 17:35
I get that , but I am trying to do just that but still couldn't do it , i don't know why.
![peek 2018-05-16 23-04](https://user-images.githubusercontent.com/24349858/40133505-a15ab058-595d-11e8-9c17-46f5baaccb16.gif)

**Comment by isantop** [comment] 2018-10-15 22:31
Closing as this is a duplicate of #175

**Closed by isantop** 2018-10-15 22:31 UTC
Labels: blocked, bug, duplicate
