### ISSUE TITLE
no close buttons in overview with pop-dark

### ISSUE THREAD

**Issue by axelmeunier** [pop-os/gtk-theme#112] opened 2018-01-02 00:01 UTC
Fresh install of Pop!_OS on Dell Precision 5510 (4K screen if it matters).
Installed Gnome tweak tool and switched to pop-dark shell theme.
In the overview, the orange close buttons have disappeared.
They are fine with the light theme.
See the screenshot (the cursor was on the top left window)
![capture d ecran de 2018-01-02 00-53-37](https://user-images.githubusercontent.com/3244556/34472047-3c687e6a-ef58-11e7-9dd4-fc8b7bd52e27.png)

**Comment by isantop** [comment] 2018-01-04 03:16
Thanks for your bug report! This is actually a duplicate of #108 and should now be fixed if you update your system.

**Closed by isantop** 2018-01-04 03:16 UTC
Labels: bug, duplicate
