### ISSUE TITLE
Wrong menubar text color on Skype with default theme

### ISSUE THREAD

**Issue by wesbluemarine** [pop-os/gtk-theme#230] opened 2018-10-27 16:24 UTC
![screenshot from 2018-10-27 18-14-22](https://user-images.githubusercontent.com/14043560/47606569-46b16780-da15-11e8-8d43-05dda6c1c7a0.png)
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
GNOME 3.30.1

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**
Skype with default pop theme

**Actual issue**
Menubar text color is too dark

**Expected behavior**
Menubar text color should be light

**Behavior in Adwaita**
Adwaita dark has light text

**Other Note (feature-request, question, etc...)**
Change menubar text color with a lighter one.

**Comment by isantop** [comment] 2018-12-06 16:55
This appears to be caused by a new Electron bug where they get the color of the menu bar from GtkMenuBar, but the color for the text from the context menu text color. In themes where the menu bar is light-text on dark and context menus are dark-text on light, (like Yaru, Adapta, Materia, Arc-Darker, Pop) this issue will occur. 

Upstream Electron bug: https://github.com/electron/electron/issues/15194

**Comment by isantop** [comment] 2019-10-23 17:11
Closing this issue as electron has been updated to correct this issue.

**Closed by isantop** 2019-10-23 17:11 UTC
Labels: bug, confirmed, upstream
