### ISSUE TITLE
Feature request: add mic and apps volume control on workbar

### ISSUE THREAD

**Issue by tridoxx** [pop-os/gtk-theme#570] opened 2022-02-02 19:10 UTC
hello, it would seem much more comfortable, that we can modify the volume of the applications from the taskbar, and not always have to go to sound settings to change the volume of an application, i use this extension, and it seems to me that the result is very good, and very comfortable for everyone

https://extensions.gnome.org/extension/858/volume-mixer/ 

![image](https://user-images.githubusercontent.com/22879539/152221238-d26f6b13-84fb-4615-afb8-81c6d5eb500f.png)

**Comment by jacobgkau** [comment] 2022-02-02 20:23
Thank you for opening an issue. This does not have to do with the Pop GTK theme, so I'm closing the issue. It also sounds like this may be related to (or a duplicate of) https://github.com/pop-os/pop/issues/1973.

**Closed by jacobgkau** 2022-02-02 20:23 UTC

**Comment by tridoxx** [comment] 2022-02-02 23:12
@jacobgkau yep i will to post on pop_os but i see that another moder move to gtktheme repo  the original.
