### ISSUE TITLE
Oversized text inputs in headerbar

### ISSUE THREAD

**Issue by trgeiger** [pop-os/gtk-theme#296] opened 2019-05-09 23:28 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
  Installed: 3.24.8-1ubuntu1

**Desktop environment:**
Gnome

**Pop version (run ```apt policy pop-gtk-theme```):**
  Installed: 4.1.4~1556120984~19.04~2988243

**Related Application and/or Shell theming (or name of widget)**
Color Picker

**Actual issue**
The text input in the headerbar of the Color Picker is oversized, with edges that are beyond the size of the other buttons. This also make the text look very small inside the input:
![color-picker](https://user-images.githubusercontent.com/18582917/57492802-e2a31200-7287-11e9-825e-10dcad2c2365.png)

You can see how this compares to the input in the Pop Shop:
![Screenshot from 2019-05-09 18-26-48](https://user-images.githubusercontent.com/18582917/57492844-0fefc000-7288-11e9-9442-24a5037feb65.png)

I'm not sure if this is an issue elsewhere.

**Expected behavior**
It should, I expect, be similar in appearance to the Pop Shop's input.

**Comment by isantop** [comment] 2019-05-10 17:29
How was this application installed? I'm not seeing it in the Pop Shop

**Comment by isantop** [comment] 2019-10-23 17:15
Appears to be a duplicate of #309

**Closed by isantop** 2019-10-23 17:15 UTC
Labels: blocked, bug
